name: chore

on: [push, pull_request]

jobs:
    prettier:
        name: Prettier check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actionsx/prettier@v2
              with:
                  args: --check .

    commitlint:
        name: Commit-lint check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 5
            - uses: wagoid/commitlint-github-action@v5
              with:
                  failOnWarnings: true

    solhint:
        name: runner / solhint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: solhint
              uses: contractshark/inject-solhint-ci@latest
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-review
                  solhint_input: 'contracts/*.sol'
